<<<<<<< HEAD
title: Resources for finance courses
<<<<<<< HEAD
description: finance slides
google_analytics:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
show_downloads: true
=======
show_downloads: false
>>>>>>> master
=======
show_downloads: false
>>>>>>> origin/gh-pages
=======
show_downloads: false
>>>>>>> origin/gh-pages

=======
title: Behavioral finance
description: behavioral finance slides
google_analytics:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
show_downloads: true
=======
show_downloads: false
>>>>>>> master
=======
show_downloads: false
>>>>>>> origin/gh-pages
=======
show_downloads: false
>>>>>>> origin/gh-pages
>>>>>>> master
theme: jekyll-theme-minimal

gems:
 - jekyll-mentions
=======
description:finance slides
google_analytics
show_downloads:false

=======
title:Behavioral finance
description:behavioral finance slides
google_analytics
show_downloads:false
>>>>>>> master
theme:jekyll-theme-minimal

gems:
- jekyll-mentions
>>>>>>> master
