<<<<<<< HEAD
<<<<<<< HEAD
title: Resources for finance courses
description:finance slides
google_analytics
show_downloads:false

=======
title:Behavioral finance
description:behavioral finance slides
google_analytics
show_downloads:false
>>>>>>> master
theme:jekyll-theme-minimal

gems:
- jekyll-mentions
=======
theme: jekyll-theme-minimal
>>>>>>> origin/gh-pages
