<<<<<<< HEAD
title: Resources for finance courses
description: finance slides
google_analytics:
<<<<<<< HEAD
show_downloads: true
=======
show_downloads: false
>>>>>>> master

=======
title: Behavioral finance
description: behavioral finance slides
google_analytics:
<<<<<<< HEAD
show_downloads: true
=======
show_downloads: false
>>>>>>> master
>>>>>>> master
theme: jekyll-theme-minimal

gems:
 - jekyll-mentions
