title: Behavioral finance
description: behavioral finance slides
google_analytics: 
show_downloads: true
<<<<<<< HEAD
theme: jekyll-theme-architect
=======
theme: jekyll-theme-cayman
>>>>>>> master

gems:
  - jekyll-mentions
